### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mschwartz** [hobbyquaker/lgtv2#10]
When I connect to my LGTV from my laptop (Windows 10) on WiFi, it asks me once to allow pairing, and then the API works.  I can restart node over and over and I'm not asked to pair again.

When I connect from a machine on ethernet (Ubuntu), I'm asked to pair (by the TV) every time I restart node.

Any ideas?

**Comment by hobbyquaker** [comment]
Seems like the saving of the keyFile doesn't work under Windows... I'm preparing the 1.4.0 release that also fixes your Issue #9 - I think that could fix the issue. Should be done this weekend.
