### ISSUE TITLE
Send screen off while playing music

### ISSUE THREAD

**Issue by rosoposo** [hobbyquaker/lgtv2#11]
Is it possible to send a command to turn the TV screen off while leaving the music playing. There is a option on the TV to turn screen off while keeping the TV running. However, it is buried in menus and it is much more convenient to trigger it through node.

**Comment by hobbyquaker** [comment]
I fear that this is not possible, can't find any api endpoint for that.

**Comment by johndbritton** [comment]
I found that if you enable IP connectivity and connect via Telnet you can send commands including `SCREEN_MUTE  screenmuteon` as documented here: http://www.proaudioinc.com/Dealer_Area/RS232C_EN_160526.pdf

I've confirmed this to work with my TV and am searching for a way to send a similar command using the `ssap` protocol used here.

cc/ https://github.com/hobbyquaker/lgtv2/issues/37
