### ISSUE TITLE
Full API documentation?

### ISSUE THREAD

**Issue by AndresSomadossi** [hobbyquaker/lgtv2#17]
Hello, I would like to see the full documentation of the API. Where can I find it? Thank you!

**Comment by hobbyquaker** [comment]
I fear there is no official api documentation. At least I didn't find one. I looked up the methods I'm using in the source of the "ConnectSDK": https://github.com/ConnectSDK/Connect-SDK-Android-Core/blob/master/src/com/connectsdk/service/WebOSTVService.java#L191
