### ISSUE TITLE
Support "Screen Mute" functionality

### ISSUE THREAD

**Issue by johndbritton** [hobbyquaker/lgtv2#37]
Does this library have a way to send the "screen mute" command?

I see that requests are sent with a `uri` and `payload` as per:

https://github.com/hobbyquaker/lgtv2/blob/d58f87092ab2d60b39a2d83d5729d524495cc096/index.js#L186-L188

I'm trying to make a change to `homebridge-webos` (which uses this library) to turn off the screen only (different than powering off the tv). This is useful to listen to music while the display is off.

I've managed to connect to my TV over IP with Telnet and sent the command `SCREEN_MUTE screenmuteon` which keeps the TV on but turns off the screen. There's also a menu option under power settings called "screen off" that I think is doing the same thing.

In `homebridge-webos` there is a list of URIs in the form `ssap://system/turnOff`:

https://github.com/merdok/homebridge-webos-tv/blob/28befc4304ec943528bfdeae88e2c33737862a1b/lib/LgTvController.js#L16-L57

Is there documentation on all of the URIs? There may be a command to send `SCREEN_MUTE` but I don't know what the URI or parameters would be. Any pointers would be helpful.

**Comment by merdok** [comment]
@johndbritton my plugin which you linked above can do that already. There is a configuration parameter which enables that functionality, just check the README: https://github.com/merdok/homebridge-webos-tv#tv-configuration-fields
`screenControl: true` in your config.json

**Comment by johndbritton** [comment]
Thank @merdok, funny enough I discovered this feature last night after building a Telnet based control myself 🤦‍♂.
