### ISSUE TITLE
how to pairing the tv

### ISSUE THREAD

**Issue by devildant** [hobbyquaker/lgtv2#7]
hello,

i try to use your module but when i try exemple (with good ip) i take systematically an error connexion refused.
could you help me ?

best regards

**Comment by hobbyquaker** [comment]
Did you enable "LG Connect Apps" on your TV? see http://www.lg.com/uk/support/product-help/CT00008334-1437131798537-others

**Comment by devildant** [comment]
hello,

i understand the problem, my bad, my tv lg use netcast 4 and i don't see the webos information inside your readme ( eyes problem).
i'am unlucky, i don't found the npm module for netcast :)
thanks and sorry

**Comment by hobbyquaker** [comment]
oh - i see. perhaps this is something for you: https://github.com/timmson/node-lgtv-api

**Comment by devildant** [comment]
hooo thx i try that :)
