### ISSUE TITLE
enable multiview app on lg webos 3.0 tv

### ISSUE THREAD

**Issue by srinidhikrs** [hobbyquaker/lgtv2#8]
Hi,

I have LG 55LH600T (web os 3.0 based) TV. In my TV , multi-view app is not enabled. 
How can I enable / install multi-view app and use multi-view feature using lgtv2?

**Comment by hobbyquaker** [comment]
As I have no WebOS 3 TV I can't test this, afaik the API has no special method for multiview. If that's just a "normal" App it would be possible to just lunch the app, but I don't know...
