### ISSUE TITLE
saveKey throws deprecation warning

### ISSUE THREAD

**Issue by mschwartz** [hobbyquaker/lgtv2#9]
In that.saveKey(), you call writeFile() without a callback.  Node complains about it.

Maybe you want to call writeFileSync() ?
Or provide a default cb that does nothing.

Cheers

I think it's on line 140.

**Comment by mschwartz** [comment]
Awesome.  You saved me  the trouble of fork/PR

**Comment by hobbyquaker** [comment]
should be fixed with 6508ceaba42e40139f399a3226b5250494538c8e

**Comment by mschwartz** [comment]
Sweet!

Thanks

**Comment by mschwartz** [comment]
I thought you might want to see what I'm doing with this module.

![image](https://user-images.githubusercontent.com/329637/28682589-5b200b02-72b2-11e7-95da-8c9c27b9e72e.png)

![image](https://user-images.githubusercontent.com/329637/28682620-702ef5e4-72b2-11e7-8961-6ba483006c72.png)

It's part of a larger home automation system I'm almost ready to release OSS.

**Comment by mschwartz** [comment]
And on phone:

![image](https://user-images.githubusercontent.com/329637/28682686-b839a85c-72b2-11e7-8159-ae938a32b09a.png)

**Comment by mschwartz** [comment]
And with volume controls open:

![image](https://user-images.githubusercontent.com/329637/28682709-cddefe82-72b2-11e7-9833-a56840bf7202.png)

The volume controls work my Denon AVR receiver, not the TV.  That's configurable in the app.

**Comment by hobbyquaker** [comment]
Nice! I'm curious and looking forward to your release! :)

**Comment by mschwartz** [comment]
I'd be interested in collaborators, too.

**Comment by hobbyquaker** [comment]
I already got a quite comprehensive home automation running, based on MQTT as central message broker, incorporating Homematic, Homematic IP, Zwave and FS20 Actuators/Sensors, several Pis, NodeMCUs, DMX-, Hue- and Lightify-Lighting, Mopidy/Airplay based multiroom Audio, a selfmade Polymer UI and Node-RED, InfluxDB/Grafana, Splunk, Nagios and more... :) Most of the Software I'm using is contained in this List: https://github.com/hobbyquaker/mqtt-smarthome 
So I can't promise if I will contribute, depends if your architecture fits in my environment ;)

**Comment by mschwartz** [comment]
I'm using MQTT connected to microservices that collect device information.

The server is express, the client is React and react-bootstrap

The microservices are all dockerized and each can run on any host on your LAN.

I'm using one central server for the home automation software, though I run the microservices on my development machine while I'm working on them.

The separation between backend, client, and collection concerns makes it all plug and play.   You can swap out the front end UI for one written in Polymer even :)

I've seen your awesome-mqtt page before.  It's truly a great resource.

Here's what the dashboard looks like on tablet:

![image](https://user-images.githubusercontent.com/329637/28687433-36c2cb26-72c3-11e7-9ccc-1eb9d3faba8e.png)

(it could use some visual love, but it's very functional)

And on phone:

![image](https://user-images.githubusercontent.com/329637/28687456-4dde58d4-72c3-11e7-892b-ca1d8eafd65f.png)

My intent is to hang tablets on the wall in some of the rooms and phones in others.  I have a $29 phone on my nightstand.

The software supports multiple dashboards so you can have one for the kitchen and a different one for the bedroom, each with appropriate display.

**Comment by hobbyquaker** [comment]
Nice, MQTT based microservices sounds good and your UI looks good too :) Put the stuff on Github and I will check it out! ;)

**Comment by mschwartz** [comment]
That's the one.  Also on dockerhub;)

**Comment by mschwartz** [comment]
BTW, I bought one of these to be my Home Automation server:

https://www.amazon.com/gp/product/B00VBNSO8U/ref=oh_aui_detailpage_o02_s01?ie=UTF8&psc=1

I had a spare 60G SSD and bought a 4G RAM stick for it.  The whole thing cost about $150.  Not a whole lot more than the Raspberry Pi (I have one of those, too), but much faster CPU, far more RAM, it runs standard Linux distros, has USB 3 and gig ethernet, etc.

**Comment by davidfrothin** [comment]
@mschwartz - Any update on your open source project.

Also how do you send commands for up and down through this?

**Comment by mschwartz** [comment]
The repos are here:

https://github.com/RoboDomo

The main server/client repo:

https://github.com/RoboDomo/RoboDomo

LGTV microservice is here:

https://github.com/RoboDomo/lgtv-microservice

The onscreen joystick logic, which sends up/down/left/right/select:

![image](https://user-images.githubusercontent.com/329637/31309398-848ddea4-ab3a-11e7-8809-f5f55ba6a1f6.png)

**Comment by mschwartz** [comment]
Here's what the LGTV screen looks like currently:

![image](https://user-images.githubusercontent.com/329637/31309419-b67d2ea6-ab3a-11e7-8af4-a13211d12575.png)

The Amazon/Hulu/etc. buttons at the bottom are fetching image URL specified by the TV and recently those image URLs started returning 404.  Probably some software update in the TV...

**Comment by davidfrothin** [comment]
@mschwartz - Awesome thanks.

I would like to add a "Screen off" feature. This is available in Settings -> ECO mode -> "Screen off" and this will turn the display off while leaving the TV and any music playing in the background.

Any idea on how I can add this button to RoboDomo? I cant see a direct method to turn screen off, so will probably have to use the KEY_LEFT, KEY_ENTER and so on and then navigate to ECO mode to turn it off?

**Comment by mschwartz** [comment]
It never occurred to me to use the screen off feature.

Adding a button to RoboDomo is trivial.  I don't know what the code would be to toggle the screen on/off, though.

**Comment by mschwartz** [comment]
The API spec is here, I think:

http://developer.lgappstv.com/TV_HELP/index.jsp?topic=%2Flge.tvsdk.references.book%2Fhtml%2FUDAP%2FUDAP%2FCurrent+channel+information+Controller+Host.htm

**Comment by mschwartz** [comment]
And the key codes are here (I don't see one for ECO modes):

http://developer.lgappstv.com/TV_HELP/index.jsp?topic=%2Flge.tvsdk.references.book%2Fhtml%2FUDAP%2FUDAP%2FCurrent+channel+information+Controller+Host.htm

**Comment by mschwartz** [comment]
More screen shots:

![image](https://user-images.githubusercontent.com/329637/31342120-a1e4295e-acc0-11e7-8d75-932e7997f3b3.png)

**Comment by mschwartz** [comment]
Images are back!

![image](https://user-images.githubusercontent.com/329637/31342151-b6667c24-acc0-11e7-9565-20e0f0075e72.png)

**Comment by davidfrothin** [comment]
@mschwartz Yes, looks like adding a button with a corresponding key code is trival on RoboDomo.

However, I cannot find the key code directly. Do you recommend me creating a chain of commands like Settings, UP, ENTER, ENTER, DOWN, DOWN, DOWN, ENTER and so on?

That way one button on the interface does all necessary steps in the background to navigate. I hope this makes sense. Do you recommend any other way?

**Comment by mschwartz** [comment]
It looks like it is missing a settings button.  From there you'd choose "disable screen" (or whatever), right?

I haven't seen this "screen off" feature on my OLEDE6P, but I do see it on my Sony Bravia TV.

I play music with Spotify and use my AVR only, with the TV entirely off.  FWIW.

**Comment by davidfrothin** [comment]
Thats fine. Thanks for your help. I will just code it to chain commands in series and give it a go.

Yes, I have a growing youtube playlist with all unique songs that are not available on spotify and others.
